[target.'cfg(and(target_os = "none", not(target_arch = "loongarch64")))']
runner = "ostool cargo-test"

[target.loongarch64-unknown-none-softfloat]
rustflags = [
  "-C",
  "link-arg=--emit-relocs",
]
